### ISSUE TITLE
scikit-learn upgrade?

### ISSUE THREAD

**Issue by sjaenick** [chklovski/CheckM2#10]
Hi,

scikit-learn 0.23.2 is pretty outdated, could this (and maybe some of the other dependencies) be upgraded to a recent release?

Thanks!

**Comment by chklovski** [comment]
Hi,

Scikit-learn in CheckM2 is used for a pre-trained MinMax scaler that transforms input data for the neural network input. The pickled scaler appears to break between versions, necessitating the requirement for a specific scikit-learn version. Future versions of CheckM2 may move away from using the scikit-learn scaler, but for now having a more outdated scikit-learn requirement doesn't affect anything within CheckM2. Tensorflow requirements may also be updated to a newer version in the future, but not before a major release that updates the prediction models.  

I would recommend having a separate conda environment for CheckM2 to avoid any conflicts for any other software.

**Comment by sjaenick** [comment]
Ok, thanks for the clarification.
