### ISSUE TITLE
Can Checkm2 be fine-tuned for euMAGs?

### ISSUE THREAD

**Issue by Andyargueasae** [chklovski/CheckM2#102]
Hello,

Just curious about whether CheckM2 can be fine-tuned to assess the eukaryotic microbial genome quality.

Andy

**Comment by chklovski** [comment]
Hi,

In principle you can use the same approach, in practice you would at least need to account for: 1) different gene calling for Eukaryotes, which is substantially more complex, and 2) very limited nature of complete, intact sequenced eukaryotic genomes for machine learning training purposes. At the moment just using BUSCO is likely to be a lot easier and more straightforward as this tool explicitly works on eukaryotic quality assessment.
