### ISSUE TITLE
RecursionError: maximum recursion depth exceeded in __instancecheck__

### ISSUE THREAD

**Issue by B-1991-ing** [chklovski/CheckM2#11]
Dear CheckM2 support team,

My HPC admin installed the CheckM2 on the HPC as an environmental module, but it doesn't work.

**My running command lines:**
module load checkm2/20220719
checkm2 predict --threads 30 --input ${binny_bins} --output-directory ${checkm2_dir}

**My error file:**
[checkm2_binny_marine.err.txt](https://github.com/chklovski/CheckM2/files/9191167/checkm2_binny_marine.err.txt)

Could you help us have a look what is wrong there?

Thank you very much.

Best,

Bing

**Comment by chklovski** [comment]
Hi, 

does checkm2 testrun complete successfully?

**Comment by B-1991-ing** [comment]
Hi Alex,

I ran the following command lines on the HPC as shown below, same errors.
module load tools computerome_utils/2.0
module load anaconda3/2021.11
module load checkm2/20220719
checkm2 testrun
checkm2 database --download --path DIAMOND_db

**Error:**
RecursionError: maximum recursion depth exceeded in __instancecheck__

Best,

Bing

**Comment by B-1991-ing** [comment]
<img width="1212" alt="Screenshot 2022-07-27 at 10 44 11" src="https://user-images.githubusercontent.com/54441633/181203411-7b4491f8-d86a-4d30-9e3d-a3336f8e7ae4.png">
When I opened the /services/tools/checkm2/20220719/bin/checkm2, is the installed checkm2 file correct?

**Comment by B-1991-ing** [comment]
The conversation between me and my HPC admin.

I email my HPC admin firstly as below,
<img width="715" alt="Screenshot 2022-07-27 at 12 20 43" src="https://user-images.githubusercontent.com/54441633/181224205-551bcbca-e5cd-4d0d-a19f-f182d3b29a5c.png">

Then, my HPC admin replied me as below,
<img width="710" alt="Screenshot 2022-07-27 at 12 21 33" src="https://user-images.githubusercontent.com/54441633/181224340-9b15494b-9fed-4830-a1ea-ca68acfe13fb.png">

**Comment by madscort** [comment]
Did you find a solution to this?

**Comment by B-1991-ing** [comment]
Not yet.
I want to use the checkm to assess my assembled MAGs, due to it not worked, I used the metawrap bin_refinement to refine the bins and get the checkm results assessed by the older version checkm.

**Comment by chklovski** [comment]
Hi, what python version are you using?

**Comment by B-1991-ing** [comment]
Hi Alex,

I am using python 3.9 installed under the anaconda3/2021.11 now.

anaconda3/2021.11: Anaconda3 2021.11 - Python 3.9 distribution for scientific computing

Best,,

Bing

**Comment by chklovski** [comment]
Hi, is this still an issue with the latest (1.0.1) version? Does it occur with the bioconda or pip install?

**Comment by B-1991-ing** [comment]
Thank you very much for message. 

I am not sure there is still any problem with the latest version --- 1.0.1, as the HPC administrator didn't reinstall it since last august.

I can't manage to use the software due to this error last august and I didn't try the latest version this year. 

Our HPC administrator installed using bioconda normally.

**Comment by chklovski** [comment]
Hi - bioconda installation wasn't available last august and was only added early this year. I would encourage you to install it that way as it's much more stable.
