### ISSUE TITLE
CommandNotFoundError

### ISSUE THREAD

**Issue by B-1991-ing** [chklovski/CheckM2#12]
Hi Alex,

I tried to run it without installing. But, after "conda activate checkm2",  **CommandNotFoundError**: Your shell has not been properly configured to use 'conda activate'. 

<img width="1359" alt="Screenshot 2022-07-27 at 10 31 44" src="https://user-images.githubusercontent.com/54441633/181200646-bf1d62ff-1dc3-436f-86dd-bf5ae6115bda.png">

Which one should I choose? If I can't see my login node after the "conda init zsh", how can I change it back - to cancel the "conda init zsh"?

Best,

Bing

**Comment by chklovski** [comment]
Hi, 

I suggest contacting your sys admin to work out how you can use private conda environments, as this error message is not specific to checkm2.

**Comment by B-1991-ing** [comment]
Thank you for your reply Alex. 

For this question, I would postpone it. 

Could you help us check what is wrong for the issue "RecursionError: maximum recursion depth exceeded in __instancecheck__ #"?

Best,

Bing
