### ISSUE TITLE
Make Prodigal and Diamond outputs reusable.

### ISSUE THREAD

**Issue by JeanMainguy** [chklovski/CheckM2#13]
Hello,

Thank you for this great tool!

I am currently adding the [metawrap bin_refinement](https://github.com/bxlab/metaWRAP#metagenomic-bin-recovery-improvements) module in a metagenomics analysis pipeline. This module uses CheckM1 and I would like to update it with CheckM2.

The metawrap bin_refinement module works as follow:

- it takes in input 3 bin sets made from different binning tools
- it creates 4 new hybrid bin sets from the combination of each of them
- then launch checkM on each bin set
- finally it finds the best version of each bin in each bin set using checkM contamination and completeness.

In this workflow, checkM is launched 7 times (on the 3 initial bin sets and on the 4 hybrid ones) but actually all the bin sets are from the same assembly which would make the Prodigal and Diamond step processing 7 times the same contigs.

As far as I can see, it's the diamond step that take most of the time in checkM2 execution. So ideally I would like to be able to reuse Prodigal and Diamond outputs to analyze any other bin sets made from the same assembly. This would greatly reduce metawrap execution time!

Thanks !
Jean

**Comment by chklovski** [comment]
I'll look into implementing a '--resume' function after diamond has been run - this might also be useful if users want to query the results of a different completeness model when they didn't initially specify it. I probably won't get to this for ~ a month though. In the mean time, if you are running checkM2 on identical bins, you can save the results of the output and reuse it? If the contigs in the bins change, the checkm2 results will also change.

**Comment by JeanMainguy** [comment]
In my case contigs do not change (their sequences and ids do not change) but their repartitions in bins change making checkM2 prediction change as well. As the contigs do not change, it would be faster to launch Diamond only once and use its result to analyze all bin sets.

I could try to make it work with the resume flag. For that I would need to launch prodigal and diamond on all contigs and shape their results specifically for each bin set mimicking what checkM2 would produce. Then I launch checkM2 with the resume flag and hopefully it will resume. It would not be the cleanest option but it would work.

**Comment by JeanMainguy** [comment]
I can try to implement a first version of the `--resume` flag and make a pull request if you are alright with that?
