### ISSUE TITLE
Database path

### ISSUE THREAD

**Issue by madscort** [chklovski/CheckM2#15]
Hi!

I am working on a HPC environment. Checkm2 is added as an environmental module.
Is there any other way of defining the path to the diamond database than using:

$ checkm2 database --setdblocation 

This causes a permission error, since the command changes a config file physically (in a module, where I do not have writing permissions).

As far as I can see, the program doesn't have a default database path.

Best

**Comment by jakobnissen** [comment]
We have hit the exact same issue now and can't easily run CheckM2 for this reason.
Our current workaround is that each individual user in our cluster downloads and installs CheckM2 independently, but that's not a great solution.

**Comment by maxibor** [comment]
Ehy @chklovski and @dparks1134 ,
This looks like it is the same issue from Checkm1 (see https://github.com/Ecogenomics/CheckM/pull/326) which has a simple fix: allow to save the configuration file somewhere else.

I believe something like this should do the trick (with an extra CLI flag to get the config path):

https://github.com/chklovski/CheckM2/blob/e563159f005344d798defb60cea4189e0be8ec92/checkm2/defaultValues.py#L5-L9
```python
class DefaultValues():
     """Default values for filenames and common constants.""" 
    def __init__(self, default_dir=None):
           if default_dir:
                self.default_dir = default_dir
           else:
                 self.default_dir = os.path.dirname(__file__)
     DATA_PATH =  os.path.join(self.default_dir , 'data') 
     MODEL_PATH = os.path.join(self.default_dir , 'models') 
     VERSION_PATH = os.path.join(self.default_dir , 'version') 
```

**Comment by madscort** [comment]
I apparently missed that the path can be set by setting the environmental variable CHECKM2DB using:
`export CHECKM2DB="path/to/database"`

**Comment by nick-youngblut** [comment]
>I apparently missed that the path can be set by setting the environmental variable CHECKM2DB using:
export CHECKM2DB="path/to/database"

It would be very helpful to add this info to https://github.com/chklovski/CheckM2#database

Better yet: adding `--database-path` to `checkm2 predict` would be awesome

**Comment by nick-youngblut** [comment]
It's also not clear from the docs that `checkm2 predict` is assuming the `CHECKM2DB` points to the `*.dmnd` file, and the parent directory MUST be named `CheckM2_database`. If the user provides something like `CheckM2_database/v1.0.1/uniref100.KO.1.dmnd`, then `checkm2 predict` returns the error: 

```
ERROR: File does not exist: CheckM2_database/uniref100.KO.1.dmnd
```

**Comment by chklovski** [comment]
Thanks, I've added a description of CHECKM2DB variable. Release [1.0.1](https://github.com/chklovski/CheckM2/releases/tag/1.0.1) now also has a `--database_path` option for `checkm2 predict`.
