### ISSUE TITLE
conda installation with tensorflow 2.9.1

### ISSUE THREAD

**Issue by KnudNorNielsen** [chklovski/CheckM2#16]
Hey,

thanks for the awesome work. Just to let you know, I ran into issues using the latest tensorflow version on conda-forge: `tensorflow 2.9.1`

```
tensorflow/core/kernels/libtfkernel_sobol_op.so: undefined symbol: _ZN10tensorflow15TensorShapeBaseINS_11TensorShapeEEC1EN4absl12lts_202111024SpanIKlEE
```

Downgrading to version `2.8.1` did not fix it. However, deleting the file as suggested [here](https://stackoverflow.com/a/67510891) seems to work (checkm2 testrun runs successfully)

Cheers

**Comment by chklovski** [comment]
Thanks for raising this. Tensorflow versions are now constrained in the checkm2.yaml file, from release [1.0.0](https://github.com/chklovski/CheckM2/releases/tag/1.0.0) onwards.
