### ISSUE TITLE
Diamond database version?

### ISSUE THREAD

**Issue by zhongwang** [chklovski/CheckM2#17]
Hi,

Testrun gives error "Error: Database was built with a different version of Diamond and is incompatible.". I tried both the latest Diamond v2.0.15 and the minimum required v2.0.4. The database was downloaded using `checkm2 database --download`.

Ideas?

Thanks!

**Comment by chklovski** [comment]
Hi, can you try installing DIAMOND v 2.0.12 or 2.0.14?

**Comment by zhongwang** [comment]
I think the culprit was a stale installation of diamond on my system. After  I removed it, the issue is solved. Thanks!
