### ISSUE TITLE
Write log to file

### ISSUE THREAD

**Issue by donovan-h-parks** [chklovski/CheckM2#2]
Hi,

This is a non-critical, quality-of-life feature request.

It would be helpful if the CheckM2 log indicated the version of the software being run and saved the log to file in the output directory. This allows people to inspect the log on crashes, send the log when reporting issues, and provides a record of what was run (including version number) when writing up study results. 

Cheers,
Donovan

**Comment by chklovski** [comment]
Implemented in v [1.0.1](https://github.com/chklovski/CheckM2/releases/tag/1.0.1)
