### ISSUE TITLE
Sequence is long

### ISSUE THREAD

**Issue by 01Carrie** [chklovski/CheckM2#20]
Hi,

Thanks for your nice tool. But I have a warning message of it, maybe because some contigs are large. As follow:
Warning:  Sequence is long (max 32000000 for training).Training on the first 32000000 bases.
So that will have any influence on the results? And how can I solve this problem?

Thank you and have a nice day.
Carrie

**Comment by chklovski** [comment]
Hi,

This is an issue with prodigal, not checkm2 itself. See here: https://github.com/hyattpd/Prodigal/issues/54

Generally CheckM2 was trained and tested using on prodigal (including large genomes that raise this warning) so this behaviour is expected and does not appear to cause serious issues with accuracy.
