### ISSUE TITLE
AttributeError: 'Predictor' object has no attribute '__set_up_prodigal_thread'

### ISSUE THREAD

**Issue by kellikmullane** [chklovski/CheckM2#21]
Hey - thanks for this tool! Really excited to start using it. I used the "Run without Installing" method to use CheckM2 and I keep getting the error: 

AttributeError: 'Predictor' object has no attribute '__set_up_prodigal_thread'

I get this with both bin/checkm2 testrun and CheckM2 predict with my own genomes. I thought it was a python version compatibility issue so I tried installing the version listed in the .yml file. I also tried actually installing it. In both cases, I either get this exact same error, or something very similar like: 

AttributeError: module '__main__' has no attribute '__spec__' or 
AttributeError: 'Predictor' object has no attribute '__reportProgress'

Any clues as to what could be going on? Not sure if it's an issue on my end or what. Appreciate any advice/help you can give!

**Comment by Mass23** [comment]
Having the same errors with my bins and the `testrun`, using the "run without installation" and "Installation" methods.

**Comment by GeoMicroSoares** [comment]
Same here! @chklovski

**Comment by emma-bell** [comment]
Me too, did anyone figure it out?

**Comment by kellikmullane** [comment]
@emma-bell I never figured it out. Ended up just going with the original CheckM. The CheckM2 documentation suggested for the organisms I was working with (Gammaproteobacteria), CheckM and CheckM2 would provide fairly similar results. Would love to get it working for future projects though, so if anyone is able to fix this issue, please drop the info on how you resolved the issue on this thread!

**Comment by chklovski** [comment]
Apologies for the late reply. If you want to try checkm2 again, please install it via bioconda and let me know if the issue persists.

**Comment by emma-bell** [comment]
Thank you @chklovski and @kellikmullane, checkm2 now works for me with the latest release (conda install) :)

**Comment by kairi-t** [comment]
I installed CheckM2 using mamba, and the test run still shows the same error message as the original post. Are there any solutions? Version is 1.1.0.
