### ISSUE TITLE
Release 1.0.0 

### ISSUE THREAD

**Issue by lfenske-93** [chklovski/CheckM2#22]
Hello together,

I am a big fan of checkm(1) and was very excited when I heard about your new version.
I would like to use checkm2 in my new workflow and wanted to ask if you can estimate when release 1.0.0 will come?

I look forward to hearing from you!
Greetings,
Linda

**Comment by chklovski** [comment]
Sorry for the delay, release [1.0.0](https://github.com/chklovski/CheckM2/releases/tag/1.0.0) is now available.
