### ISSUE TITLE
Latest software and database versions

### ISSUE THREAD

**Issue by donovan-h-parks** [chklovski/CheckM2#25]
It would be helpful if the README indicated what the most recent version of the software and database. It would also help to indicate when these were last updated. This is particularly an issue for the database since without downloading a new version there is currently no way to know if it has been updated.

**Comment by DininduSenanayake** [comment]
Using this thread as it is related : 

On top of the READEME, can we populate the relevant information on releases which is empty at the moment  (or tags at least) https://github.com/chklovski/CheckM2/releases ?   🙂
Not having the release notes is bit of an issue for  admins  maintaining software stacks  on clusters,etc as

**Comment by chklovski** [comment]
Thanks for raising this. Changelog and releases are now implemented.
