### ISSUE TITLE
Remove intermediate files

### ISSUE THREAD

**Issue by donovan-h-parks** [chklovski/CheckM2#3]
Hi,

This is a non-critical, quality-of-life feature request.

It would be nice to have a flag the allowed all intermediate files to be removed. Namely, the `diamond_ouput` and `protein_files` directories. These are often not of interest and require non-trivial disk space when running large numbers of genomes (e.g. ~2G for 1000 genomes). Obviously, such things can be handled by auxiliary scripts, but it would be a nice QoL feature to have built-in to the software.

Cheers,
Donovan

**Comment by chklovski** [comment]
This has been added in release [1.0.0](https://github.com/chklovski/CheckM2/releases/tag/1.0.0)
