### ISSUE TITLE
CheckM2 too conservative?

### ISSUE THREAD

**Issue by xinehc** [chklovski/CheckM2#32]
Hi,

I used checkM2 to check the completeness and contamination of some RefSeq complete genomes. I found that even if some genomes have an anomalous (extremely low) number of ribosomal proteins, checkM2 still mark them as high quality. Here are two examples.

Accession | Name | Completeness | Contamination
---| ---| ---| ---
GCF_016653575.1  |Bacillus sp. TK-2             |                         98.77      |   0.08
GCF_014235785.1 | Bacillus sp. PAMC26568                       |          92.50  |       0.00

CheckM1 gives 80.36% and 69.64% for these two genomes, which seems more reasonable. So I was wondering what could be the cause of this?

**Comment by donovan-h-parks** [comment]
Hi,

CheckM v1 and v2 are independent methods for assessing genome quality. CheckM v1 uses marker genes and thus is likely more sensitive to the presence or absence of ribosomal proteins. This is NOT necessarily good. 

GCF_016653575.1 has a genome size of 5.2 Mb which is nearly identical to the 98.9% complete genome GCF_006384875.1 which is the species cluster representative for these genomes in GTDB (see: https://gtdb.ecogenomic.org/genome?gid=GCF_006384875.1). This would suggest that GCF_016653575.1 is a fairly complete genome and perhaps has some assembly issues that are resulting in low number of ribosomal proteins being identified (?). 

GCF_014235785.1 has a genome size of 3.9 Mb. Other genomes in the same GTDB species cluster have a size of 4.6 Mb, 4.8 Mb, and 5.1  Mb and are all estimated to be >98% complete by CheckM v1. Genome size can vary substantially between strains of the same species, but on the surface it would seem that an estimate around 80% complete might be best so both the CheckM v1 and v2 estimates may be a bit inaccurate for this genome.

Cheers,
Donovan
