### ISSUE TITLE
Increase protein search stringency? (Low-homology problem)

### ISSUE THREAD

**Issue by GabeAl** [chklovski/CheckM2#34]
The original checkm used hmmsearch with an HMM database of marker genes. This is arguably the most accurate and sensitive method for detecting remote homology in protein alignment, particularly when a sequence is notably diverged from any individual reference sequence in the database but still maintains the characteristic conservation pattern in the highly conserved sites (identified in an MSA). 

The second most sensitive protein search is blastp and its ilk (pairwise sensitive alignment). 

In third place is the default "fast" search mode of diamond. The difference between diamond's default "fast" and its --ultra-sensitive is well-documented (including in its own publication), with difference increasing with sequence divergence. The difference between pairwise blastp and a well-constructed HMM from a rigorous MSA is also well understood in phylogenetics and remote homology detection.

Can you justify why hmms have been dropped in favor of pairwise protein alignments, and further can you explain why the default "fast" mode is used in the more-heuristic diamond aligner rather than blastp or the near-equivalent (but faster) --ultra-sensitive mode of diamond?

Further, I see uniref100 was used (which does not contain many proteins found in metagenomes, e.g. MGNify) as a proxy for annotating proteins with KEGG IDs (which also relies on assignment of those original uniref proteins from likely an even older version of KEGG using further heuristic assignments). Propagating heuristics from the initial KEGG assignments to those proteins, and then from those proteins to new proteins, has potential for error especially with more distant homologies (which are less accurate anyway with the diamond default blastp fast parameters). 

Most strikingly, these multiple layers of abstractions are unnecessary when the actual KEGG HMMs already exist publicly (see KoFamKoala's FTP) and are the standard in assigning KEGG IDs de novo. It seems checkm2 is going through a long game of telephone, chaining multiple loose heuristics together and relying on a machine learning black box to sort through it all. Why not simply pull or redistribute the subset of HMMs used by the model and align to those with hmmsearch? It's direct, more sensitive, more exact, and can potentially lead to just one unified model for all homologies. 

Curious to hear your thoughts.

Thanks!
Gabe

**Comment by chklovski** [comment]
Hi, thank you for your interest in CheckM2. This was a largely practical and empirical decision. 

During initial validation, we compared using DIAMOND-based KEGG annotations with HMM-based KO, PFAM and TIGRFAM annotations, as well as more sensitive diamond search mode. All had roughly equivalent accuracy (including on highly novel lineages) during cross-validation across multiple machine learning algorithms and configurations in predicting genome quality. However, HMM-based methods are substantially slower, which is a significant factor when having to annotate > 1 million synthetic genomes that form the basis of the CheckM2 models - now, and going forward into the future, as MAG databases expand rapidly. 

Given that it seemed that there was little accuracy to be gained from using HMM-search-based annotation methods, we went with DIAMOND-based KEGG annotation, as grouping KEGG's KO id's into pathways yielded a modest increase in accuracy and the entire approach was substantially faster. 

You're right that uniref100 is not comprehensive and KEGG-based IDs are a (much) smaller subsection of that, but even using alternative annotations such as STRING (diamond fast or ultra-sensitive search modes) yielded generally comparative accuracy despite a much bigger range of input vectors and/or higher alignment accuracy. We will continue testing accuracy in future CheckM2 releases and may switch to alternate annotation methods in future CheckM2 milestone releases (e.g. STRING or EggNOG) as databases expand and accuracy differences become more substantial, and especially as more high-quality genomes of unusual and novel lineages become available to more accurately gauge the effect of more distant protein homology. 

Hope this helps.

Cheers,
Alex

**Comment by GabeAl** [comment]
Thanks for these comments. This invites a couple more points for the sake of lively discussion:

- Have you considered manually sparsifying the model (or including a sparsity penalty in feature selection/input to a non-sparsifying model)? Checkm1 used a tiny fraction of the hmm family space (despite using a different space per lineage after pplacer ran to establish which marker set to use). In principle, especially given your finding that larger annotation vectors from STRING did not improve accuracy, checkm2 could further "feature select" to a smaller but highly predictive set of HMMs. This has twofold advantages; first, it would likely be a more generalizable set of annotations that are equally predictive yet less sensitive to noise due to biological conservation, and second, it would allow deeper homology search. Highly conserved marker selection + deeper homology search = potentially better generalization to unseen data.
- Point well taken about the need for speed when benchmarking synthetic genomes for model creation. But it's worth pointing out as well that this is a "front-loaded" cost, paid only once (or a few times) during development only, whereas the benefits to downstream users with dozens/hundreds (even thousands+) of MAGs, may be cumulatively greater, amortizing the cost. Combined with potentially winnowing down the list of actually informative annotations (sparsification mentioned above), this could further reduce runtime cost (again at the expense of time spent development/building the models)!

**Comment by chklovski** [comment]
Thanks for the reply - sorry for the late response. We are looking into alternative annotation systems & will test out a potentially smaller pool of HMM models, including as complementary annotation, depending on speed & accuracy of the tests.
