### ISSUE TITLE
Runs out of /tmp space. Needs option to specify temp dir

### ISSUE THREAD

**Issue by GabeAl** [chklovski/CheckM2#35]
On modern systems, /tmp redirects to RAM. 
On a 1tb RAM node, the 500gb of RAM in /tmp is easily exhausted during the diamond run if multiple instances are running with hundreds/thousands of MAGs each.

The solution is to allow the user to specify temporary directory. If this is already possible, I don't see a flag for it.

Results are sometimes silently corrupt if the diamond blast file is truncated once /tmp is exhausted.

**Comment by chklovski** [comment]
Thanks for raising this. Implemented in release [1.0.1](https://github.com/chklovski/CheckM2/releases/tag/1.0.1)
