### ISSUE TITLE
Some questions about NCBI archaeal genomes predicted as Low-quality draft

### ISSUE THREAD

**Issue by ZongzhiWu** [chklovski/CheckM2#36]
Dear Chklovski, 
I performed quality prediction of all NCBI Refseq archaea genomes (n=1360, Downloaded on 2023-01-06) using CheckM2. 
As results, a total of 52 NCBI Refseq archaeal genomes were predicted as Low-quality draft (Completion<50% with Contamination<10%).
I used to think the Refseq archaea genomes should be predicted as High-quality draft.
Their status in Refseq seems to be 'suppressed'. And most of them are partial, but they are still listed as Refseq.
The quality report of the 52 NCBI Refseq archaeal genomes are shown as follow:
_GCF_000372505.1 7.02    0.02    Neural Network (Specific Model) 11      0.944   31458   308.0   233168  0.24    239     None
GCF_000382725.2 10.42   0.02    Neural Network (Specific Model) 11      0.89    6144    265.09005628517826      474487  0.35    533 None
GCF_000192595.1 5.21    0.01    Neural Network (Specific Model) 11      0.856   24163   216.18333333333334      45346   0.35    60  None
GCF_000192615.1 15.3    0.0     Neural Network (Specific Model) 11      0.915   31882   253.72727272727272      100212  0.35    121 None
GCF_000382765.1 20.16   0.27    Neural Network (Specific Model) 11      0.938   22214   338.16582914572865      429678  0.46    398 None
GCF_000380865.1 15.27   0.09    Neural Network (Specific Model) 11      0.831   28977   183.99468085106383      248182  0.54    376 None
GCF_000380685.1 38.25   0.3     Neural Network (Specific Model) 11      0.905   25175   278.3911764705882       624620  0.63    680 None
GCF_000402935.1 20.33   0.0     Neural Network (Specific Model) 11      0.9     40278   266.9569536423841       267561  0.58    302 None
GCF_000402915.1 49.95   0.0     Neural Network (Specific Model) 11      0.914   20269   266.9151436031332       667371  0.62    766 None
GCF_000402965.1 41.12   0.24    Neural Network (Specific Model) 11      0.92    16921   269.7848258706468       703726  0.57    804 None
GCF_000398485.1 31.96   0.33    Neural Network (Specific Model) 11      0.904   24529   280.14964788732397      525966  0.63    568 None
GCF_000405905.1 46.62   0.06    Neural Network (Specific Model) 11      0.908   26075   268.1021377672209       741841  0.62    842 None
GCF_000398505.1 40.54   0.76    Neural Network (Specific Model) 11      0.902   31581   271.7974683544304       640245  0.57    711 None
GCF_000405925.1 15.44   0.04    Neural Network (Specific Model) 11      0.905   11690   244.55392156862746      164795  0.63    204 None
GCF_000398525.1 20.52   0.0     Neural Network (Specific Model) 11      0.909   18425   261.6632302405498       249792  0.6     291 None
GCF_000398545.1 11.45   0.0     Neural Network (Specific Model) 11      0.922   26696   285.12820512820514      252228  0.49    273 None
GCF_000398565.1 23.54   0.08    Neural Network (Specific Model) 11      0.922   16590   268.9789029535865       412511  0.52    474 None
GCF_000398585.1 10.93   0.0     Neural Network (Specific Model) 11      0.875   13490   256.3568281938326       198883  0.63    227 None
GCF_000405745.1 19.49   0.0     Neural Network (Specific Model) 11      0.898   29390   263.81024096385545      291490  0.45    332 None
GCF_000402475.1 18.96   0.0     Neural Network (Specific Model) 11      0.921   13811   247.81496062992127      204081  0.34    254 None
GCF_000404305.1 47.56   0.23    Gradient Boost (General Model)  11      0.895   35139   255.77304964539007      361035  0.38    423 None
GCF_000371945.1 40.24   0.75    Neural Network (Specific Model) 11      0.863   8800    217.33881897386254      775531  0.39    1033None
GCF_000375605.1 22.4    0.03    Neural Network (Specific Model) 11      0.863   10933   218.59248554913296      523162  0.3     692 None
GCF_000372145.1 31.64   0.5     Neural Network (Specific Model) 11      0.861   12646   222.76753246753248      593616  0.33    770 None
GCF_000375665.1 17.76   0.1     Neural Network (Specific Model) 11      0.876   7044    215.02351097178683      467463  0.43    638 None
GCF_000376005.1 33.98   0.03    Neural Network (Specific Model) 11      0.875   9339    226.77879714576963      758618  0.3     981 None
GCF_000375985.1 39.12   0.87    Neural Network (Specific Model) 11      0.889   12223   247.26695842450766      758640  0.53    914 None
GCF_000376025.1 40.3    2.51    Neural Network (Specific Model) 11      0.882   10391   239.4714765100671       965738  0.64    1192None
GCF_000349625.1 14.5    0.35    Neural Network (Specific Model) 11      0.813   13721   219.9969465648855       529171  0.43    655 None
GCF_000364885.1 25.91   0.9     Neural Network (Specific Model) 11      0.833   10367   211.4298469387755       593453  0.31    784 None
GCF_000349685.1 33.53   0.25    Neural Network (Specific Model) 11      0.857   12904   236.6001589825119       1037251 0.37    1258None
GCF_001315925.1 46.15   1.02    Gradient Boost (General Model)  11      0.811   34784   130.14622178606476      1920275 0.59    4076None
GCF_000484955.1 28.56   0.67    Neural Network (Specific Model) 11      0.925   12024   234.4126679462572       394893  0.36    521 None
GCF_000484915.1 20.97   0.27    Neural Network (Specific Model) 11      0.86    16111   248.33558178752108      512945  0.25    593 None
GCF_000402255.1 28.8    0.01    Neural Network (Specific Model) 11      0.905   18127   230.38832487309645      299490  0.33    394 None
GCF_000415945.1 37.89   0.21    Neural Network (Specific Model) 4       0.801   2040945 216.5785992217899       2040945 0.61    2570None
GCF_000494185.1 40.45   0.22    Neural Network (Specific Model) 11      0.92    19616   271.79487179487177      688171  0.54    780 None
GCF_000494125.1 38.14   0.25    Neural Network (Specific Model) 11      0.907   25175   280.8230884557721       617045  0.61    667 None
GCF_000494165.1 49.89   0.0     Neural Network (Specific Model) 11      0.915   24396   268.8887399463807       654645  0.64    746 None
GCF_000496235.1 46.53   0.66    Neural Network (Specific Model) 4       0.84    304570  303.180260707635        2876249 0.59    2685None
GCF_000746695.1 30.61   1.16    Neural Network (Specific Model) 11      0.923   64295   239.33985765124555      435918  0.33    562 None
GCF_000746705.1 41.51   0.01    Neural Network (Specific Model) 11      0.91    20264   229.83549783549785      522768  0.34    693 None
GCF_902158755.1 37.31   0.0     Neural Network (Specific Model) 11      0.909   32599   274.0403587443946       803504  0.47    892 None
GCF_012927665.1 9.09    0.0     Neural Network (Specific Model) 11      0.934   50193   357.15441176470586      155723  0.45    136 None
GCF_012927685.1 22.19   0.11    Neural Network (Specific Model) 11      0.871   28343   259.7018469656992       337773  0.47    379 None
GCF_012927695.1 45.54   0.66    Neural Network (Specific Model) 11      0.91    63768   273.8136826783115       619468  0.44    687 None
GCF_012927715.1 25.28   0.1     Neural Network (Specific Model) 11      0.937   28455   271.8103975535168       284101  0.42    327 None
GCF_012927765.1 31.69   0.01    Neural Network (Specific Model) 11      0.918   41938   281.08061002178647      420777  0.44    459 None
GCF_905067475.1 34.87   0.05    Neural Network (Specific Model) 11      0.866   16637   259.2754662840746       623357  0.41    697 None
GCF_905067525.1 24.48   0.0     Neural Network (Specific Model) 11      0.87    14935   264.9917355371901       551157  0.44    605 None
GCF_905067565.1 26.05   0.11    Neural Network (Specific Model) 11      0.872   9703    242.27331606217618      640119  0.44    772 None
GCF_920984865.1 17.86   2.06    Neural Network (Specific Model) 11      0.599   607503  89.31677465802736       607503  0.24    1389None_

**Comment by donovan-h-parks** [comment]
Hi,

A genome being in RefSeq does not necessarily imply an assembly is of good quality though NCBI makes a best effort to achieve this. I spot checked a few genomes using CheckM v1 which also indicates these genomes are incomplete:
 ```
GCF_000372505.1: 3.74%
GCF_000192595.1 3.74%
GCF_000192615.1: 17.6%
GCF_000382765.1: 26.2%
```

It is possible CheckM v1 and v2 are both incorrect though these are independent methods for estimating genome quality. At least some of these genomes are now recognized at NCBI as being partial and have been suppressed from RefSeq, e.g.:
https://www.ncbi.nlm.nih.gov/assembly/GCF_000372505.1/
https://www.ncbi.nlm.nih.gov/assembly/GCF_000382765.1/.

Hope this helps.

Cheers,
Donovan

**Comment by ZongzhiWu** [comment]
Many thanks! Really helpful to me.
