### ISSUE TITLE
[Discussion] Testing on microeukaryotic organisms as a negative control

### ISSUE THREAD

**Issue by jolespin** [chklovski/CheckM2#46]
I did a quick test on some [marine plastisphere eukaryotes](https://figshare.com/articles/dataset/Genome_assemblies_gene_models_gene_annotations_taxonomy_classifications_clusters_and_counts_tables/20263974) I've binned out using my [VEBA pipeline](https://bmcbioinformatics.biomedcentral.com/articles/10.1186/s12859-022-04973-8) to determine whether or not I should run [Tiara](https://academic.oup.com/bioinformatics/article/38/2/344/6375939).  

![image](https://user-images.githubusercontent.com/9061708/217079524-d8404d32-e050-44e6-be3f-2864dcba4538.png)

I noticed that eukaryotes are returned with high completeness and contamination.  With my default settings completeness ≥50 and contamination < 10 I would have removed these automatically but I wasn't sure if this info was useful for your research.

Good luck with the publication!  Looking forward to checking out the final draft once its out. And thanks again for putting this up on bioconda and pypi as it has made my prokaryotic binning pipeline MUCH more straightforward.

Please close if this too far out of scope.

**Comment by chklovski** [comment]
Thanks for noting this! The way CheckM2 was trained was using a ceiling of ~35-40% contamination, meaning that contamination numbers beyond that do not scale meaningfully with real biology. A reported contamination score of more than 35% is CheckM2 stating the genome is completely unusable, regardless of what it is or how complete it is. 

If you throw enough genes at it however, completeness scores do seem to creep up. We will look into whether explicitly training CheckM2 to disregard eukaryotic genomes as 0% complete may help.
