### ISSUE TITLE
Version of Numpy installed from conda

### ISSUE THREAD

**Issue by julianzaugg** [chklovski/CheckM2#47]
Hey Alex,

Just bringing the issue discussed here to your attention: [https://github.com/rhysnewell/aviary/issues/92#issue](https://github.com/rhysnewell/aviary/issues/92#issuecomment-1423561738)

I have had this issue pop up once with a student running a snakemake rule using CheckM2 in [Aviary](https://github.com/rhysnewell/aviary), but the issue has not occurred for others (at least recently). So it is unclear if it an issue that will frequently occur.

```
AttributeError: module 'numpy' has no attribute 'typeDict'
[Fri Jan 27 06:54:28 2023]
Error in rule checkm_semibin:
    jobid: 20
    input: data/semibin_bins/done
    output: data/semibin_bins/checkm2_out, data/semibin_bins/checkm.out
    conda-env: /srv/home/USER/.conda/envs/096cdc4ad5efd911ad0acd1888e0a504_
    shell:
        touch data/semibin_bins/checkm.out; export CHECKM2DB=/srv/db/checkm2_data/0.1.3/CheckM2_database//uniref100.KO.1.dmnd; echo "Using CheckM2 database $CHECKM2DB"; checkm2 predict -i data/semibin_bins/output_recluster_bins// -x fa -o data/semibin_bins/checkm2_out -t 60 --force; cp data/semibin_bins/checkm2_out/quality_report.tsv data/semibin_bins/checkm.out
        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)
```

**Comment by chklovski** [comment]
Sorry for the delay - hopefully this shouldn't happen with the bioconda installation of checkm2. Please reopen if issue persists.
