### ISSUE TITLE
specify dependecy versions

### ISSUE THREAD

**Issue by nick-youngblut** [chklovski/CheckM2#48]
The current [conda env yaml](https://github.com/chklovski/CheckM2/blob/main/checkm2.yml) doesn't specify the specific allowable versions for some dependencies, but this can lead to conflicts, such as issues with specific versions of numpy, grpcio, and scipy. 

See https://github.com/chklovski/CheckM2/issues/38  for the numpy-grpcio conflict, and see https://github.com/scipy/scipy/releases/tag/v1.10.0 for the numpy requirements for the most recent version of scipy.

**Comment by nick-youngblut** [comment]
Which version of scipy was/is used for checkm2 development?

**Comment by nick-youngblut** [comment]
There are also potential conflicts between numpy and tensorflow, such as:

```
error: numpy 1.24.2 is installed but numpy~=1.19.2 is required by {'tensorflow'}
```

... when tensorflow is specified as `tensorflow>=2.1.0,<2.6.0`

**Comment by nick-youngblut** [comment]
I tried the following env yaml:

```
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.9
  - scikit-learn=0.23.2
  - h5py=2.10.0
  - numpy=1.19.2
  - diamond=2.0.4
  - tensorflow>=2.1.0,<2.6.0
  - lightgbm=3.2.1
  - pandas<=1.4.0
  - scipy=1.9
  - prodigal>=2.6.3
  - setuptools
  - requests
  - packaging
  - tqdm
```

...but this generates the error:

```
 grpcio 1.32.0 is installed but grpcio>=1.48.2 is required by {'tensorboard'}
```

...at least when using `mambaorg/micromamba:1.1.0` as the base image in my Dockerfile.

**Comment by nick-youngblut** [comment]
If I try:

```
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.9
  - grpcio
  - scikit-learn=0.23.2
  - h5py=2.10.0
  - numpy>=1.19.2
  - diamond=2.0.4
  - tensorflow>=2.1.0,<2.6.0
  - lightgbm=3.2.1
  - pandas<=1.4.0
  - scipy>=1.8
  - prodigal>=2.6.3
  - setuptools
  - requests
  - packaging
  - tqdm
```

...then I get:

```
error: numpy 1.24.2 is installed but numpy~=1.19.2 is required by {'tensorflow'}
```

**Comment by nick-youngblut** [comment]
I tried explicitly running the setup as in the README:

```
git clone --recursive https://github.com/chklovski/checkm2.git --branch 1.0.1
cd checkm2
mamba env create -f checkm2.yml 
python setup.py install
```

This results in the following error:

```
error: grpcio 1.32.0 is installed but grpcio>=1.48.2 is required by {'tensorboard'}
```

I'm using `Ubuntu 20.04.5` for this test.

**Comment by nick-youngblut** [comment]
To deal with this issue for now, I just cleared out the dependencies set  in `setup.py`. In other words: `install_requires=()`. This allowed me to install & run checkm2 successfully.

**Comment by chklovski** [comment]
Thanks for testing this. I've implemented your solution of removing requirements from the setup.py as this seems to resolve a lot of conflicts. Please re-open if issue surfaces again.
