### ISSUE TITLE
Installation issue: wrong file version provided

### ISSUE THREAD

**Issue by susheelbhanu** [chklovski/CheckM2#5]
Hey all, 

I ran `python setup.py install` and am getting the following error:
```
installing package data to build/bdist.linux-x86_64/egg
running install_data
error: can't copy 'checkm2/version/version_hashes_0.1.1.json': doesn't exist or not a regular file
```

I checked the folder the file in there is `version_hashes_0.1.2.json`, so please update the `setup.py` file.

Thank you!

**Comment by chklovski** [comment]
Fixed, thanks!
