### ISSUE TITLE
Visualization

### ISSUE THREAD

**Issue by namnh7** [chklovski/CheckM2#51]
Is there any way to visualize checkm2 output? Can we use checkm(1) plotting features for this?

Thanks!!

**Comment by chklovski** [comment]
Hi, as the output and underlying algorithm for checkm2 is entirely different from checkm1, checkm1 plotting features are not going to be applicable. All the data from checkm2 output should be contained in the quality_report.tsv file (which can be visualised using third party tools if needed). Hope this helps.
