### ISSUE TITLE
Testrun discrepancies

### ISSUE THREAD

**Issue by hannahrieg** [chklovski/CheckM2#54]
Hello,

I downloaded checkM2 and did the test run but it gives different output than what is stated. I cannot find my mistake. Otherwise it runs perfectly also on other genomes. But I am not sure if I can trust the numbers now.

this is my output:
 Name  Completeness  Contamination         Completeness_Model_Used  Translation_Table_Used
TEST1        100.00           0.74 Neural Network (Specific Model)                      11
TEST2         98.54           0.21 Neural Network (Specific Model)                      11
TEST3         98.75           0.51 Neural Network (Specific Model)                      11

**Comment by chklovski** [comment]
Hi, sorry for the confusion.  The output in the README was for CheckM1 - your output is correct for CheckM2.

**Comment by hannahrieg** [comment]
Thank you so much for your quick answer!

**Comment by Clayton-Markham** [comment]
It seems that the output for the README has still not been updated to reflect the correct results for the CheckM2 testrun FYI.
