### ISSUE TITLE
Include `mamba` option for installation instructions

### ISSUE THREAD

**Issue by shaman-narayanasamy** [chklovski/CheckM2#61]
Dear authors/developers,

Thank you for your continued work and maintenance on `checkm2`. 

Just a quick suggestion; Could you please include installation instructions for `mamba` as well: 

`mamba install -c bioconda -c conda-forge checkm2`

Briefly, I was attempting to install on my `slurm` HPC system using `conda`, but even a 24hr passive job was not sufficient to complete the installation. It seems to be solving environment for the longest time. I made sure to update my `conda` installation before installing `checkm2`. I then switched to `mamba`, which completed the installation within 15 minutes..! Adding `mamba` installation options to the `README` could save the next person who encounters such issues some time :)

Cheers,
Shaman

**Comment by chklovski** [comment]
Excellent suggestion, will be added to README - thanks!
