### ISSUE TITLE
Big Data Analysis

### ISSUE THREAD

**Issue by RoyaRahmani** [chklovski/CheckM2#67]
Hi,
I have a question regarding the data capacity limitations of CheckM2. 
I'm interested in knowing the maximum data size or number of genomes that can be processed in a single run.
 Could you please provide some information on this?
Thank you!

**Comment by chklovski** [comment]
Hi,

CheckM2 is designed to do bulk processing of many genomes at once. I've run it on 225,000 at once to assess the entirety of GTDB release 202, which finished successfully, so you should be able to run it on tens to hundreds of thousands of genomes at a time without a big spike in computing requirements.
