### ISSUE TITLE
pypi and bioconda install

### ISSUE THREAD

**Issue by nick-youngblut** [chklovski/CheckM2#7]
Are there any plans to get CheckM2 on pypi (and then bioconda)? 

Given how many pipelines/workflows include CheckM v1, it will be very helpful to have CheckM2 on bioconda

**Comment by chklovski** [comment]
Hi - yes, this will be done in the near future.

**Comment by SilasK** [comment]
The future is now. Any reason to wait for the bioconda package?

The only thing I would need is a release from the official GitHub, repo. I guess this one.

**Comment by SilasK** [comment]
Ah, and can you clarify the version? 
Your latest commits contained info about v 0.1.3. But you have version 2. so it should be 2.1.3 .

Please don't with checkm2 v1.0.0 .

**Comment by chklovski** [comment]
Sorry, currently swamped with work - I will try to make a release and add to bioconda over the next month. CheckM2 models may also may get updated to be in line with the newest GTDB release as well before I do that. Apologies for the delay. 

Regarding versions, CheckM2 is a stand-alone tool that operates in many ways very differently from CheckM1, and therefore it makes sense to version it independently. So CheckM2 v1 may happen.

**Comment by chklovski** [comment]
I will make a release and add to bioconda over the next month or so. CheckM2 models may also may get updated to be in line with the newest GTDB release as well before I do that. Apologies for the delay.

Regarding versions, CheckM2 is a stand-alone tool that operates in many ways very differently from CheckM1, and therefore it makes sense to version it independently. So CheckM2 v1 may happen.

**Comment by jolespin** [comment]
Looking forward to this being available on conda.  Once it's on Bioconda I will update my pipelines to use this instead of CheckM version 1.x.

Good luck with the publication btw.

**Comment by atyakhtmpg** [comment]
Hello, the Bioconda is highly anticipated!

**Comment by chklovski** [comment]
Hi, thanks for your patience. Bioconda and pypi installation is now available from version 1.0.1 onwards.

**Comment by jolespin** [comment]
Awesome! Going to start adding it into my pipelines
