### ISSUE TITLE
Include more stats

### ISSUE THREAD

**Issue by Sumsarium** [chklovski/CheckM2#71]
It would be awesome if you could include more stats in the output file, particularly strain heterogeneity (as in Checkm) and contig counts.

**Comment by chklovski** [comment]
Hi, strain heterogeneity is not something CheckM2 calculates, as it does not use counts of single-copy marker genes occurring more than once, which is the basis for the strain heterogeneity calculation in CheckM1. Contig count stats are implemented into CheckM2 as of version 1.0.2.
