### ISSUE TITLE
CheckM2 missing files and result inconsistencies

### ISSUE THREAD

**Issue by gkatahon** [chklovski/CheckM2#9]
Great tool, but I have some questions.

Is there a way to see, with checkM2, how many markers were used and found, and which ones these are? The output it gives seems very basic.

Additionally, I am getting some inconsistent results and wanted to ask your opinion about them. Especially because it concerns DPANN and it was mentioned checkM2 works better for that group.

From a Nanopore dataset of corrected reads with Canu, I made Flye assemblies. Once with supplying the corrected reads as --nano-raw and once as --nano-corr.
These two assemblies (hereafter nano-raw and nano-corr) were used in metaWRAP for binning.

The nano-raw assembly gives one Concoct bin (1 contig) of a DPANN, and a Maxbin2 bin (2 contigs) of the same DPANN. Basically, the maxbin2 bin is the contig present in the Concoct bin plus a 7.8kb contig.
The nano-corr assembly gives one Concoct bin (1 contig) of a DPANN, and a Maxbin2 bin (2 contigs) of the same DPANN. Basically, the maxbin2 bin is the contig present in the Concoct bin plus a 7.8kb contig.

The large contig of the bins the same size (2bp difference) in the different assemblies and they are 99.956% similar to each other.
The 7.8kb contig present in the Maxbin2 bins of the different assemblies is identical.

When I run checkM2, however, results seem a bit odd.

nano-raw concoct bin: 60.96% complete; 0.54% contamination
nano-raw Maxbin2 bin: 61.05% complete; 0.53% contamination
nano-corr concoct bin: 60.74% complete; 0.63% contamination
nano-corr Maxbin2 bin: 60.74% complete; 0.63% contamination

Could you explain why that 7.8kb contig makes a difference in completeness in one of the bins, and not the other? The contig is identical, so potential changes should be the same.

When I run checkM1 on the 4 bins, they all have a completeness of 64.65% and 0% contamination.

Thanks a lot for the help/info on this!

**Comment by chklovski** [comment]
Hi, 

CheckM2 does not use (single-copy) marker genes but a full set of KEGG protein annotation, as well as total counts of each amino acid, number of coding sequences, and length of genome as inputs. 

As a result, small variations in these inputs can produce minor variations in output as is seen here. As CheckM1 uses only single-copy marker genes, it is less likely to vary with small bin changes. 

Functionally your bin is 61% complete and 0.5% contaminated as estimated by CheckM2. Variations of <1% at this level of completeness is far below the error variance of CheckM2 (and even more of CheckM1) and is functionally meaningless (well below the resolution capacity of either tool). 

You can also check the 'diamond_output' folder which contains all KEGG annotations identified in any given bin/contig. If the KEGG annotations are the same, then the difference is down to minor changes in genomic properties. Hope this answers your question.

**Comment by chklovski** [comment]
Closed due to inactivity.
